apiVersion: v1
kind: ConfigMap
metadata:
  name: trivy-config
  namespace: trivy-system
data:
  trivy.yaml: |
    scan:
      scanners:
        - vuln
        - secret
        - config
      timeout: 5m
    report:
      format: sarif
      output: /tmp/trivy-results
    vuln:
      type: library
    secret:
      config: /etc/trivy/secret.yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trivy-scanner
  namespace: trivy-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trivy-scanner
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "daemonsets", "statefulsets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: trivy-scanner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: trivy-scanner
subjects:
- kind: ServiceAccount
  name: trivy-scanner
  namespace: trivy-system
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: trivy-image-scan
  namespace: trivy-system
spec:
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: trivy-scanner
          containers:
          - name: trivy
            image: aquasecurity/trivy:latest
            command:
            - trivy
            - image
            - --format
            - sarif
            - --output
            - /tmp/scan-results.sarif
            - --severity
            - HIGH,CRITICAL
            - --ignore-unfixed
            - $(IMAGE)
            env:
            - name: IMAGE
              value: "nginx:latest"
            volumeMounts:
            - name: scan-results
              mountPath: /tmp
          volumes:
          - name: scan-results
            emptyDir: {}
          restartPolicy: Never