apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aegis-security
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/aegis-kubernetes-framework
    targetRevision: HEAD
    path: manifests/security
  destination:
    server: https://kubernetes.default.svc
    namespace: aegis-security
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  revisionHistoryLimit: 10