apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-access-sa
  namespace: default
  annotations:
    # Replace with your actual IAM role ARN from Terraform output
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/cluster-s3-access-role
  labels:
    app: s3-access-sa
    aegis.example: irsa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: s3-access-role
  labels:
    aegis.example: irsa
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: s3-access-binding
  labels:
    aegis.example: irsa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: s3-access-role
subjects:
- kind: ServiceAccount
  name: s3-access-sa
  namespace: default