apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-latest-tag
  annotations:
    policies.kyverno.io/title: Disallow Latest Tag
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
spec:
  validationFailureAction: enforce
  rules:
  - name: require-image-tag
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: "An image tag is required."
      pattern:
        spec:
          containers:
          - image: "*:*"
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-run-as-nonroot
  annotations:
    policies.kyverno.io/title: Require Run As Non Root User
    policies.kyverno.io/category: Pod Security Standards
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
spec:
  validationFailureAction: enforce
  rules:
  - name: run-as-non-root
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: "Running as root is not allowed. Set securityContext.runAsNonRoot to true or securityContext.runAsUser to a non-zero value."
      pattern:
        spec:
          securityContext:
            runAsNonRoot: true
          containers:
          - securityContext:
              allowPrivilegeEscalation: false
              privileged: false
              readOnlyRootFilesystem: true
              runAsNonRoot: true
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-images
  annotations:
    policies.kyverno.io/title: Verify Image Signatures and Digests
    policies.kyverno.io/category: Security
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
spec:
  validationFailureAction: enforce
  background: false
  rules:
  - name: verify-image-signatures
    match:
      resources:
        kinds:
        - Pod
    verifyImages:
    - imageReferences:
      - "ghcr.io/aegis-framework/*"
      mutateDigest: true
      key: |-
        -----BEGIN PUBLIC KEY-----
        MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE8nXRh950IZbRj8Ra/N9sbqOPQv7
        8XaSm451y8TxLGpN3PoT3kFBA4v8PhCL6pKHyE5H8WTZQMhcWZBm8PjYg==
        -----END PUBLIC KEY-----
      attestors:
        count: 1
        entries:
        - keyless:
            subject: "https://github.com/aegis-framework/*"
            issuer: "https://token.actions.githubusercontent.com"
  - name: verify-argoproj-images
    match:
      resources:
        kinds:
        - Pod
    verifyImages:
    - imageReferences:
      - "quay.io/argoproj/*"
      mutateDigest: true
      key: |-
        -----BEGIN PUBLIC KEY-----
        MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE8nXRh950IZbRj8Ra/N9sbqOPQv7
        8XaSm451y8TxLGpN3PoT3kFBA4v8PhCL6pKHyE5H8WTZQMhcWZBm8PjYg==
        -----END PUBLIC KEY-----
      attestors:
        count: 1
        entries:
        - keyless:
            subject: "https://github.com/argoproj/*"
            issuer: "https://token.actions.githubusercontent.com"
  - name: verify-istio-images
    match:
      resources:
        kinds:
        - Pod
    verifyImages:
    - imageReferences:
      - "docker.io/istio/*"
      mutateDigest: true
      key: |-
        -----BEGIN PUBLIC KEY-----
        MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE8nXRh950IZbRj8Ra/N9sbqOPQv7
        8XaSm451y8TxLGpN3PoT3kFBA4v8PhCL6pKHyE5H8WTZQMhcWZBm8PjYg==
        -----END PUBLIC KEY-----
      attestors:
        count: 1
        entries:
        - keyless:
            subject: "https://github.com/istio/*"
            issuer: "https://token.actions.githubusercontent.com"
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-host-path
  annotations:
    policies.kyverno.io/title: Restrict Host Path Volumes
    policies.kyverno.io/category: Security
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
spec:
  validationFailureAction: enforce
  rules:
  - name: block-host-path
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: "HostPath volumes are not allowed."
      deny:
        conditions:
          all:
          - key: "{{ request.object.spec.volumes[].hostPath }}"
            operator: NotEquals
            value: ""
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-network-policies
  annotations:
    policies.kyverno.io/title: Require Network Policies
    policies.kyverno.io/category: Security
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Namespace
spec:
  validationFailureAction: enforce
  rules:
  - name: require-default-deny
    match:
      resources:
        kinds:
        - Namespace
    validate:
      message: "Namespaces must have a default-deny network policy."
      deny:
        conditions:
          all:
          - key: "{{ request.object.metadata.name }}"
            operator: NotIn
            value: ["kube-system", "kube-public", "kube-node-lease", "default"]
          - key: |
              {{ length(request.object.spec) }}
            operator: Equals
            value: 0
---
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-image-registries
  annotations:
    policies.kyverno.io/title: Restrict Image Registries
    policies.kyverno.io/category: Security
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
spec:
  validationFailureAction: enforce
  background: false
  rules:
  - name: allowed-registries
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: "Images must be from approved registries only."
      anyPattern:
      - spec:
          containers:
          - image: "ghcr.io/aegis-framework/*"
      - spec:
          containers:
          - image: "quay.io/argoproj/*"
      - spec:
          containers:
          - image: "docker.io/istio/*"
      - spec:
          containers:
          - image: "gcr.io/kyverno/*"
      - spec:
          containers:
          - image: "k8s.gcr.io/*"
      - spec:
          containers:
          - image: "registry.k8s.io/*"

---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-privilege-escalation
  annotations:
    policies.kyverno.io/title: Disallow Privilege Escalation
    policies.kyverno.io/category: Pod Security Standards
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
spec:
  validationFailureAction: enforce
  rules:
  - name: block-privilege-escalation
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: "Privilege escalation is not allowed."
      pattern:
        spec:
          containers:
          - securityContext:
              allowPrivilegeEscalation: false
          securityContext:
            runAsNonRoot: true

---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-resource-limits
  annotations:
    policies.kyverno.io/title: Require Resource Limits
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
spec:
  validationFailureAction: enforce
  rules:
  - name: check-resource-limits
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: "All containers must have resource limits defined."
      pattern:
        spec:
          containers:
          - resources:
              limits:
                memory: "?*"
                cpu: "?*"
              requests:
                memory: "?*"
                cpu: "?*"